apiVersion: v1
kind: Pod
metadata:
  name: one-pod
  namespace: homework
spec:
  volumes:
    - name: one-volume
      emptyDir: {}
  
  initContainers:
    - name: init-container
      image: busybox
      command: ['sh', '-c', 'wget -O /init/index.html http://samlib.ru']
      volumeMounts:
        - name: one-volume
          mountPath: /init

  containers:
    - name: nginx-container
      image: nginx:alpine
      ports:
        - containerPort: 8000
      volumeMounts:
        - name: one-volume
          mountPath: /homework
      lifecycle:
        preStop:
          exec:
            command: ["sh", "-c", "rm -f /homework/index.html"]